<a href="https://colab.research.google.com/github/danielduartt/Numpy-Python/blob/main/2_Indexa%C3%A7%C3%A3o_e_cortes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


##**Indexação e Cortes (Slices) de Arrays**




*   Acessando Valores e alterando



In [22]:
#array unidimensional
a = np.arange(10, 21)
print(a)
print(a[0])
print(a[-1])
print('~'*60)
#array bidimensional
b = np.random.rand(5,5) # 5 x 5
print("primeira linha: ", b[0]) #retorna a linhas inteira
print("[1,1]: ", b[0][0]) #primeiro valor na primeira coluna e primeira linha )
b[0][1] = 10 # ou b[0, 1] = 10
print("Alteração: ", b[0])


[10 11 12 13 14 15 16 17 18 19 20]
10
20
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
primeira linha:  [0.84419416 0.08888252 0.2304312  0.03004694 0.87966361]
[1,1]:  0.8441941614774505
Alteração:  [ 0.84419416 10.          0.2304312   0.03004694  0.87966361]




*   Slice = corte de um array




In [29]:
#Array Unidimensional ou de N dimensões
a = np.arange(10, 21)
print(a)
print("-------------------------------------------")
print(a[2: 5]) # vai da posição 2 até a 4, posso passar o passo tbm (star : stop - 1: step)
print("-------------------------------------------")
print(a[2: 9: 2]) # do 2 até o 8 pulando de 2 em 2
print("-------------------------------------------")
print(a[:5]) # 0 até a 4
print("-------------------------------------------")
print(a[2:]) # 2 até o final do array
print("-------------------------------------------")
print(a[:]) # array inteiro
print()
print("----------------Array Bidimensional------------------")
b = np.random.rand(5, 5)
print(b)
print("-------------------------------------------")
print(b[0:2]) # b[x : y, z], x e y então relacionados as linhas, o z é referente a coluna, caso não coloque nada
             # pega todas. Nesse caso estou pegando as duas primeira linhas com todas as colunas
print("-------------------------------------------")
print(b[0 : 2, 3]) # aqui estou pegando a primeira e a segunda linha da colunas 3





[10 11 12 13 14 15 16 17 18 19 20]
-------------------------------------------
[12 13 14]
-------------------------------------------
[12 14 16 18]
-------------------------------------------
[10 11 12 13 14]
-------------------------------------------
[12 13 14 15 16 17 18 19 20]
-------------------------------------------
[10 11 12 13 14 15 16 17 18 19 20]

----------------Array Bidimensional------------------
[[0.30986531 0.15683027 0.14350612 0.65229845 0.66088942]
 [0.36444447 0.13656393 0.61536857 0.43706413 0.19637343]
 [0.92055165 0.51382146 0.47659244 0.43959646 0.83715014]
 [0.5387265  0.89883816 0.76757271 0.13073469 0.6717771 ]
 [0.35634688 0.13227189 0.13043834 0.33787984 0.3070074 ]]
-------------------------------------------
[[0.30986531 0.15683027 0.14350612 0.65229845 0.66088942]
 [0.36444447 0.13656393 0.61536857 0.43706413 0.19637343]]
-------------------------------------------
[0.65229845 0.43706413]
